apiVersion: camunda.crossplane.io/v1alpha1
kind: Client
metadata:
  name: coffee-shop-zeebe-client
spec:
  forProvider:
    clusterID: 984bc013-defd-4550-a375-476c3b6ced96
  writeConnectionSecretToRef:
    name: service-worker-client
    namespace: coffee-shop-crossplane
  providerConfigRef:
    name: c8-org-arabica
