
resources:
  - deployment.yaml
# Comment this in if you want to use crossplane
#  - coffee-shop-client.yaml

configMapGenerator:
  - name: coffee-shop-bpmn
    options:
      disableNameSuffixHash: true
    files:
    - coffee-shop.bpmn
